In [9]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:,.2f}'.format

In [3]:
clean = pd.read_csv('clean_data_after_eda.csv')
clean.head(2)

,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,...,var_6m_price_off_peak_var,var_6m_price_peak_var,var_6m_price_mid_peak_var,var_6m_price_off_peak_fix,var_6m_price_peak_fix,var_6m_price_mid_peak_fix,var_6m_price_off_peak,var_6m_price_peak,var_6m_price_mid_peak,churn
0,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,...,0.000131,0.000041,0.000908,2.086294,99.530517,44.235794,2.086425,99.530558,44.236702,1
1,d29c2c54acc38ff3c0614d0a653813dd,MISSING,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,...,0.000003,0.001218,0.000000,0.009482,0.000000,0.000000,0.009485,0.001218,0.000000,0

In [4]:
clean.columns

Index(['id', 'channel_sales', 'cons_12m', 'cons_gas_12m', 'cons_last_month',
       'date_activ', 'date_end', 'date_modif_prod', 'date_renewal',
       'forecast_cons_12m', 'forecast_cons_year', 'forecast_discount_energy',
       'forecast_meter_rent_12m', 'forecast_price_energy_off_peak',
       'forecast_price_energy_peak', 'forecast_price_pow_off_peak', 'has_gas',
       'imp_cons', 'margin_gross_pow_ele', 'margin_net_pow_ele', 'nb_prod_act',
       'net_margin', 'num_years_antig', 'origin_up', 'pow_max',
       'var_year_price_off_peak_var', 'var_year_price_peak_var',
       'var_year_price_mid_peak_var', 'var_year_price_off_peak_fix',
       'var_year_price_peak_fix', 'var_year_price_mid_peak_fix',
       'var_year_price_off_peak', 'var_year_price_peak',
       'var_year_price_mid_peak', 'var_6m_price_off_peak_var',
       'var_6m_price_peak_var', 'var_6m_price_mid_peak_var',
       'var_6m_price_off_peak_fix', 'var_6m_price_peak_fix',
       'var_6m_price_mid_peak_fix', 'var_6m_price_off_peak',
       'var_6m_price_peak', 'var_6m_price_mid_peak', 'churn'],
      dtype='object')

In [6]:
clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14606 entries, 0 to 14605
Data columns (total 44 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              14606 non-null  object
 1   channel_sales                   14606 non-null  object
 2   cons_12m                        14606 non-null  int64
 3   cons_gas_12m                    14606 non-null  int64
 4   cons_last_month                 14606 non-null  int64
 5   date_activ                      14606 non-null  object
 6   date_end                        14606 non-null  object
 7   date_modif_prod                 14606 non-null  object
 8   date_renewal                    14606 non-null  object
 9   forecast_cons_12m               14606 non-null  float64
 10  forecast_cons_year              14606 non-null  int64
 11  forecast_discount_energy        14606 non-null  float64
 12  forecast_meter_rent_12m         14606 non-null  float64
 13  forecast_price_energy_off_peak  14606 non-null  float64
 14  forecast_price_energy_peak      14606 non-null  float64
 15  forecast_price_pow_off_peak     14606 non-null  float64
 16  has_gas                         14606 non-null  object
 17  imp_cons                        14606 non-null  float64
 18  margin_gross_pow_ele            14606 non-null  float64
 19  margin_net_pow_ele              14606 non-null  float64
 20  nb_prod_act                     14606 non-null  int64
 21  net_margin                      14606 non-null  float64
 22  num_years_antig                 14606 non-null  int64
 23  origin_up                       14606 non-null  object
 24  pow_max                         14606 non-null  float64
 25  var_year_price_off_peak_var     14606 non-null  float64
 26  var_year_price_peak_var         14606 non-null  float64
 27  var_year_price_mid_peak_var     14606 non-null  float64
 28  var_year_price_off_peak_fix     14606 non-null  float64
 29  var_year_price_peak_fix         14606 non-null  float64
 30  var_year_price_mid_peak_fix     14606 non-null  float64
 31  var_year_price_off_peak         14606 non-null  float64
 32  var_year_price_peak             14606 non-null  float64
 33  var_year_price_mid_peak         14606 non-null  float64
 34  var_6m_price_off_peak_var       14606 non-null  float64
 35  var_6m_price_peak_var           14606 non-null  float64
 36  var_6m_price_mid_peak_var       14606 non-null  float64
 37  var_6m_price_off_peak_fix       14606 non-null  float64
 38  var_6m_price_peak_fix           14606 non-null  float64
 39  var_6m_price_mid_peak_fix       14606 non-null  float64
 40  var_6m_price_off_peak           14606 non-null  float64
 41  var_6m_price_peak               14606 non-null  float64
 42  var_6m_price_mid_peak           14606 non-null  float64
 43  churn                           14606 non-null  int64
dtypes: float64(29), int64(7), object(8)
memory usage: 4.9+ MB

In [10]:
clean.describe().T

,count,mean,std,min,25%,50%,75%,max
cons_12m,"14,606.00","159,220.29","573,465.26",0.00,"5,674.75","14,115.50","40,763.75","6,207,104.00"
cons_gas_12m,"14,606.00","28,092.38","162,973.06",0.00,0.00,0.00,0.00,"4,154,590.00"
cons_last_month,"14,606.00","16,090.27","64,364.20",0.00,0.00,792.50,"3,383.00","771,203.00"
forecast_cons_12m,"14,606.00","1,868.61","2,387.57",0.00,495.00,"1,112.88","2,401.79","82,902.83"
forecast_cons_year,"14,606.00","1,399.76","3,247.79",0.00,0.00,314.00,"1,745.75","175,375.00"
forecast_discount_energy,"14,606.00",0.97,5.11,0.00,0.00,0.00,0.00,30.00
forecast_meter_rent_12m,"14,606.00",63.09,66.17,0.00,16.18,18.80,131.03,599.31
forecast_price_energy_off_peak,"14,606.00",0.14,0.02,0.00,0.12,0.14,0.15,0.27
forecast_price_energy_peak,"14,606.00",0.05,0.05,0.00,0.00,0.08,0.10,0.20
forecast_price_pow_off_peak,"14,606.00",43.13,4.49,0.00,40.61,44.31,44.31,59.27
imp_cons,"14,606.00",152.79,341.37,0.00,0.00,37.39,193.98,"15,042.79"
margin_gross_pow_ele,"14,606.00",24.57,20.23,0.00,14.28,21.64,29.88,374.64
margin_net_pow_ele,"14,606.00",24.56,20.23,0.00,14.28,21.64,29.88,374.64
nb_prod_act,"14,606.00",1.29,0.71,1.00,1.00,1.00,1.00,32.00
net_margin,"14,606.00",189.26,311.80,0.00,50.71,112.53,243.10,"24,570.65"
num_years_antig,"14,606.00",5.00,1.61,1.00,4.00,5.00,6.00,13.00
pow_max,"14,606.00",18.14,13.53,3.30,12.50,13.86,19.17,320.00
var_year_price_off_peak_var,"14,606.00",0.00,0.00,0.00,0.00,0.00,0.00,0.00
var_year_price_peak_var,"14,606.00",0.00,0.00,0.00,0.00,0.00,0.00,0.00
var_year_price_mid_peak_var,"14,606.00",0.00,0.00,0.00,0.00,0.00,0.00,0.00
var_year_price_off_peak_fix,"14,606.00",0.69,11.01,0.00,0.00,0.01,0.01,344.57
var_year_price_peak_fix,"14,606.00",2.12,13.57,0.00,0.00,0.00,0.00,271.16
var_year_price_mid_peak_fix,"14,606.00",0.89,5.70,0.00,0.00,0.00,0.00,74.76
var_year_price_off_peak,"14,606.00",0.69,11.01,0.00,0.00,0.01,0.01,344.57
var_year_price_peak,"14,606.00",2.12,13.57,0.00,0.00,0.00,0.00,271.16
var_year_price_mid_peak,"14,606.00",0.89,5.70,0.00,0.00,0.00,0.00,74.76
var_6m_price_off_peak_var,"14,606.00",0.00,0.00,0.00,0.00,0.00,0.00,0.01
var_6m_price_peak_var,"14,606.00",0.00,0.00,0.00,0.00,0.00,0.00,0.00
var_6m_price_mid_peak_var,"14,606.00",0.00,0.00,0.00,0.00,0.00,0.00,0.00
var_6m_price_off_peak_fix,"14,606.00",0.92,18.22,0.00,0.00,0.00,0.01,525.99
var_6m_price_peak_fix,"14,606.00",1.46,13.76,0.00,0.00,0.00,0.00,399.47
var_6m_price_mid_peak_fix,"14,606.00",0.63,5.90,0.00,0.00,0.00,0.00,80.88
var_6m_price_off_peak,"14,606.00",0.92,18.22,0.00,0.00,0.00,0.01,525.99
var_6m_price_peak,"14,606.00",1.46,13.76,0.00,0.00,0.00,0.00,399.47
var_6m_price_mid_peak,"14,606.00",0.63,5.90,0.00,0.00,0.00,0.00,80.88
churn,"14,606.00",0.10,0.30,0.00,0.00,0.00,0.00,1.00

In [11]:
L = ['date_activ', 'date_end', 'date_modif_prod', 'date_renewal']

for i in L:
 clean[i] = pd.to_datetime(clean[i])

In [12]:
clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14606 entries, 0 to 14605
Data columns (total 44 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              14606 non-null  object
 1   channel_sales                   14606 non-null  object
 2   cons_12m                        14606 non-null  int64
 3   cons_gas_12m                    14606 non-null  int64
 4   cons_last_month                 14606 non-null  int64
 5   date_activ                      14606 non-null  datetime64[ns]
 6   date_end                        14606 non-null  datetime64[ns]
 7   date_modif_prod                 14606 non-null  datetime64[ns]
 8   date_renewal                    14606 non-null  datetime64[ns]
 9   forecast_cons_12m               14606 non-null  float64
 10  forecast_cons_year              14606 non-null  int64
 11  forecast_discount_energy        14606 non-null  float64
 12  forecast_meter_rent_12m         14606 non-null  float64
 13  forecast_price_energy_off_peak  14606 non-null  float64
 14  forecast_price_energy_peak      14606 non-null  float64
 15  forecast_price_pow_off_peak     14606 non-null  float64
 16  has_gas                         14606 non-null  object
 17  imp_cons                        14606 non-null  float64
 18  margin_gross_pow_ele            14606 non-null  float64
 19  margin_net_pow_ele              14606 non-null  float64
 20  nb_prod_act                     14606 non-null  int64
 21  net_margin                      14606 non-null  float64
 22  num_years_antig                 14606 non-null  int64
 23  origin_up                       14606 non-null  object
 24  pow_max                         14606 non-null  float64
 25  var_year_price_off_peak_var     14606 non-null  float64
 26  var_year_price_peak_var         14606 non-null  float64
 27  var_year_price_mid_peak_var     14606 non-null  float64
 28  var_year_price_off_peak_fix     14606 non-null  float64
 29  var_year_price_peak_fix         14606 non-null  float64
 30  var_year_price_mid_peak_fix     14606 non-null  float64
 31  var_year_price_off_peak         14606 non-null  float64
 32  var_year_price_peak             14606 non-null  float64
 33  var_year_price_mid_peak         14606 non-null  float64
 34  var_6m_price_off_peak_var       14606 non-null  float64
 35  var_6m_price_peak_var           14606 non-null  float64
 36  var_6m_price_mid_peak_var       14606 non-null  float64
 37  var_6m_price_off_peak_fix       14606 non-null  float64
 38  var_6m_price_peak_fix           14606 non-null  float64
 39  var_6m_price_mid_peak_fix       14606 non-null  float64
 40  var_6m_price_off_peak           14606 non-null  float64
 41  var_6m_price_peak               14606 non-null  float64
 42  var_6m_price_mid_peak           14606 non-null  float64
 43  churn                           14606 non-null  int64
dtypes: datetime64[ns](4), float64(29), int64(7), object(4)
memory usage: 4.9+ MB

In [13]:
clean['avg_monthly_cons'] = clean['cons_12m']/12

monthly scale of yearly consumption

In [15]:
clean['consumption_deviation'] = clean['cons_last_month'] = clean['avg_monthly_cons']

checking if last month consumption is unusual or not

In [17]:
clean['forecast_error'] = clean['forecast_cons_12m'] - clean['cons_12m']

gap between forcasted and actual

In [18]:
clean['contract_duration'] = clean['date_end'] - clean['date_activ']

checking for the long contract customer

In [ ]:
clean['days_to_modify_product'] = (
    clean['date_modif_prod'] - clean['date_activ']
).dt.days

how fast customer modify product or service

In [19]:
clean['margin_difference'] = (
    clean['margin_gross_pow_ele']
    - clean['margin_net_pow_ele']
)

gap between gross and net margin

In [21]:
clean['consumption_per_power'] = (
    clean['cons_12m'] / clean['pow_max'].replace(0 , np.nan)
)

usage according to subscribed power

In [22]:
clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14606 entries, 0 to 14605
Data columns (total 50 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              14606 non-null  object
 1   channel_sales                   14606 non-null  object
 2   cons_12m                        14606 non-null  int64
 3   cons_gas_12m                    14606 non-null  int64
 4   cons_last_month                 14606 non-null  float64
 5   date_activ                      14606 non-null  datetime64[ns]
 6   date_end                        14606 non-null  datetime64[ns]
 7   date_modif_prod                 14606 non-null  datetime64[ns]
 8   date_renewal                    14606 non-null  datetime64[ns]
 9   forecast_cons_12m               14606 non-null  float64
 10  forecast_cons_year              14606 non-null  int64
 11  forecast_discount_energy        14606 non-null  float64
 12  forecast_meter_rent_12m         14606 non-null  float64
 13  forecast_price_energy_off_peak  14606 non-null  float64
 14  forecast_price_energy_peak      14606 non-null  float64
 15  forecast_price_pow_off_peak     14606 non-null  float64
 16  has_gas                         14606 non-null  object
 17  imp_cons                        14606 non-null  float64
 18  margin_gross_pow_ele            14606 non-null  float64
 19  margin_net_pow_ele              14606 non-null  float64
 20  nb_prod_act                     14606 non-null  int64
 21  net_margin                      14606 non-null  float64
 22  num_years_antig                 14606 non-null  int64
 23  origin_up                       14606 non-null  object
 24  pow_max                         14606 non-null  float64
 25  var_year_price_off_peak_var     14606 non-null  float64
 26  var_year_price_peak_var         14606 non-null  float64
 27  var_year_price_mid_peak_var     14606 non-null  float64
 28  var_year_price_off_peak_fix     14606 non-null  float64
 29  var_year_price_peak_fix         14606 non-null  float64
 30  var_year_price_mid_peak_fix     14606 non-null  float64
 31  var_year_price_off_peak         14606 non-null  float64
 32  var_year_price_peak             14606 non-null  float64
 33  var_year_price_mid_peak         14606 non-null  float64
 34  var_6m_price_off_peak_var       14606 non-null  float64
 35  var_6m_price_peak_var           14606 non-null  float64
 36  var_6m_price_mid_peak_var       14606 non-null  float64
 37  var_6m_price_off_peak_fix       14606 non-null  float64
 38  var_6m_price_peak_fix           14606 non-null  float64
 39  var_6m_price_mid_peak_fix       14606 non-null  float64
 40  var_6m_price_off_peak           14606 non-null  float64
 41  var_6m_price_peak               14606 non-null  float64
 42  var_6m_price_mid_peak           14606 non-null  float64
 43  churn                           14606 non-null  int64
 44  avg_monthly_cons                14606 non-null  float64
 45  consumption_deviation           14606 non-null  float64
 46  forecast_error                  14606 non-null  float64
 47  contract_duration               14606 non-null  timedelta64[ns]
 48  margin_difference               14606 non-null  float64
 49  consumption_per_power           14606 non-null  float64
dtypes: datetime64[ns](4), float64(35), int64(6), object(4), timedelta64[ns](1)
memory usage: 5.6+ MB

In [23]:
clean.head()

,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,...,var_6m_price_off_peak,var_6m_price_peak,var_6m_price_mid_peak,churn,avg_monthly_cons,consumption_deviation,forecast_error,contract_duration,margin_difference,consumption_per_power
0,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0.00,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,...,2.09,99.53,44.24,1,0.00,0.00,0.00,1096 days,0.00,0.00
1,d29c2c54acc38ff3c0614d0a653813dd,MISSING,4660,0,388.33,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,...,0.01,0.00,0.00,0,388.33,388.33,"-4,470.05",2566 days,0.00,337.68
2,764c75f661154dac3a6c254cd082ea7d,foosdfpfkusacimwkcsosbicdxkicaua,544,0,45.33,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,...,0.00,0.00,0.00,0,45.33,45.33,-496.04,2192 days,0.00,39.26
3,bba03439a292a1e166f80264c16191cb,lmkebamcaaclubfxadlmueccxoimlema,1584,0,132.00,2010-03-30,2016-03-30,2010-03-30,2015-03-31,240.04,...,0.00,0.00,0.00,0,132.00,132.00,"-1,343.96",2192 days,0.00,120.00
4,149d57cf92fc41cf94415803a877cb4b,MISSING,4425,0,368.75,2010-01-13,2016-03-07,2010-01-13,2015-03-09,445.75,...,0.00,0.00,0.00,0,368.75,368.75,"-3,979.25",2245 days,0.00,223.48

In [25]:
price = pd.read_csv('price_data (1).csv')
price.head(2)

,id,price_date,price_off_peak_var,price_peak_var,price_mid_peak_var,price_off_peak_fix,price_peak_fix,price_mid_peak_fix
0,038af19179925da21a25619c5a24b745,2015-01-01,0.15,0.00,0.00,44.27,0.00,0.00
1,038af19179925da21a25619c5a24b745,2015-02-01,0.15,0.00,0.00,44.27,0.00,0.00

In [26]:
price['price_date'] = pd.to_datetime(price['price_date'])

In [27]:
price.head()

,id,price_date,price_off_peak_var,price_peak_var,price_mid_peak_var,price_off_peak_fix,price_peak_fix,price_mid_peak_fix
0,038af19179925da21a25619c5a24b745,2015-01-01,0.15,0.00,0.00,44.27,0.00,0.00
1,038af19179925da21a25619c5a24b745,2015-02-01,0.15,0.00,0.00,44.27,0.00,0.00
2,038af19179925da21a25619c5a24b745,2015-03-01,0.15,0.00,0.00,44.27,0.00,0.00
3,038af19179925da21a25619c5a24b745,2015-04-01,0.15,0.00,0.00,44.27,0.00,0.00
4,038af19179925da21a25619c5a24b745,2015-05-01,0.15,0.00,0.00,44.27,0.00,0.00

In [28]:
price.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193002 entries, 0 to 193001
Data columns (total 8 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  193002 non-null  object
 1   price_date          193002 non-null  datetime64[ns]
 2   price_off_peak_var  193002 non-null  float64
 3   price_peak_var      193002 non-null  float64
 4   price_mid_peak_var  193002 non-null  float64
 5   price_off_peak_fix  193002 non-null  float64
 6   price_peak_fix      193002 non-null  float64
 7   price_mid_peak_fix  193002 non-null  float64
dtypes: datetime64[ns](1), float64(6), object(1)
memory usage: 11.8+ MB

In [29]:
price.columns

Index(['id', 'price_date', 'price_off_peak_var', 'price_peak_var',
       'price_mid_peak_var', 'price_off_peak_fix', 'price_peak_fix',
       'price_mid_peak_fix'],
      dtype='object')

In [30]:
price['month'] = price['price_date'].dt.month

In [31]:
price[['price_date','month']].head()

  price_date  month
0 2015-01-01      1
1 2015-02-01      2
2 2015-03-01      3
3 2015-04-01      4
4 2015-05-01      5

In [32]:
jan = price[price['month'] == 1]
dec = price[price['month'] == 12]

In [33]:
jan = jan[['id','price_off_peak_var']]
dec = dec[['id','price_off_peak_var']]

In [34]:
jan.rename(columns={'price_off_peak_var':'jan_price'}, inplace=True)
dec.rename(columns={'price_off_peak_var':'dec_price'}, inplace=True)

In [35]:
price_diff = jan.merge(dec,on='id')

In [36]:
price_diff['off_peak_diff_dec_jan'] = (
    price_diff['dec_price'] -
    price_diff['jan_price']
)

In [37]:
clean = clean.merge(
    price_diff[['id','off_peak_diff_dec_jan']],
    on='id',
    how='left'
)

In [38]:
clean[['id', 'off_peak_diff_dec_jan']].head()

                                 id  off_peak_diff_dec_jan
0  24011ae4ebbe3035111d65fa7c15bc57                   0.02
1  d29c2c54acc38ff3c0614d0a653813dd                  -0.00
2  764c75f661154dac3a6c254cd082ea7d                  -0.00
3  bba03439a292a1e166f80264c16191cb                  -0.00
4  149d57cf92fc41cf94415803a877cb4b                  -0.01

In [39]:
clean['off_peak_diff_dec_jan'].describe()

count   14,584.00
mean        -0.00
std          0.01
min         -0.15
25%         -0.01
50%         -0.01
75%         -0.00
max          0.17
Name: off_peak_diff_dec_jan, dtype: float64